# Use an official Node.js runtime as a parent image
FROM node:16

# Set the working directory to /app
WORKDIR /app

COPY ./package*.json ./

# Install any needed dependencies
RUN npm install

COPY . .

# Build your React application for production
# RUN npm run build

# Expose port 3000 for your React application
EXPOSE 3000

# Run the command to start your React application
CMD [ "npm", "run", "start" ]






